---
title: "Pipeline example"
format: html
---

# Introduction

This file shows how to utilize the pipeline built here to generate an ERC network for some species of interest. In this case, we will be focusing on *D. melanogaster* and utilizing all annotated Dipteran genomes available on ncbi, alongside *C. felis* as an outgroup. We assume that you are using some form of Unix, but the pipeline has been tested on Ubuntu running in WSL2. It *should* work in both Windows and on MacOS, assuming all necessary software is installed and visible to your CLI.

# Initializing the software, installing all dependencies.

Before we run any analyses, we will require several tools. 1) Julia v 1.11+

Once Julia is installed, run the below script:

```{julia}
using Pkg
Pkg.add("DrWatson")
Pkg.activate("CoEvolution")
Pkg.instantiate()
```

This might run for a while, as it will compile any necessary packages for later scripts. While that is running, install the following on your system.

2)  [Mafft](https://github.com/rcedgar/muscle/releases)
3)  [Diamond](https://github.com/bbuchfink/diamond/wiki)
4)  [iqTree2](http://www.iqtree.org/#download)

If you would like to use this pipeline to download and prep data, make sure you have installed:

5)  [datasets-cli](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/command-line-tools/download-and-install/)
6)  [ncbi e-utils](https://www.ncbi.nlm.nih.gov/books/NBK179288/)

If you also wish to run co-introgression analysis, you'll need:

7)  [Dsuite](https://github.com/millanek/Dsuite)
8)  [bcftools](https://www.htslib.org/download/)

Hopefully Julia is up and running at this point, so we can begin on the main steps of the analysis.

# Defining major parameters

The below codeblock is where you can define the major parameters for the pipeline (taxon, focal species, outgroup, directory). The nature of this pipeline means it might be a good idea to just have these in the `Project.toml` file, but I know people will be more afraid of editing a file they can't see versus running code-blocks in a somewhat familiar interface.

```{julia}
using DrWatson
@quickactivate "CoEvolution"

#Set these values for your own analysis. Taxon can be given as plain-text, but use ncbi taxon ids when possible.
taxon = "Dipterans"
data_dir = datadir("dipterans/") #The default place for all of the files, but give the absolute path of wherever data is meant to go otherwise.
#Specify the focal species for the analysis.
focal= "D_melanogaster"
#Specify an outgroup - necessary for ASTRAL-IV to adequately make a species tree.
outgroup_ncbi_id = "Ctenocephalides felis"
outgroup_name = "C_felis"
```

# Prep data

You can prepare the data in one of two ways. First, you can define the taxon of interest in the code block below and download data using our internal script. This will poll the NCBI `datasets` database to find any annotated, chromosome level assemblies within the taxon specified, download their protein sequences and gff files and place them in the data directory in the `seqs` folder.

```{julia}
#SKIP THIS IF YOU ARE USING YOUR OWN DATA!
include srcdir("Finding_orthologs.jl")
isdir(data_dir) || mkdir(data_dir)
download_and_prep_sequences(taxon)
download_and_prep_sequences(outgroup_ncbi_id;level=scaffold)
```

# Finding orthologs for focal species.

We first identify orthologous sequences for all genes within the focal species. This is done in the following code block, most functions are defined in the `src\Finding_orthologs.jl` script. Fill out parameters in the blanks below to point to the correct files.

```{julia}
include(srcdir("Finding_orthologs.jl"))
include(srcdir("ERC_functions.jl"))
```

```{julia}
#Now run the below, and go off to grab some tea, or take a break for the day.
species = replace.(filter(endswith(".faa"),readdir(data_dir*"seqs/")),r".faa"=>"")
all_orthologs = find_orths(focal,species,data_dir)
#If the above gets interrupted - delete any .tsv files of size 0 in your `data_dir\blast` directory, and run it again. It will only run analyses for missing pairs of species.
using Arrow

Arrow.write(data_dir*focal*"_orthologs.arrow",all_orthologs)

#And if things break later, you can always load in the all_orthologs dataframe with `all_orthologs=DataFrame(Arrow.Table(data_dir*focal*"_orthologs.arrow))"`

#The next step takes a while, since parallelization is doable but not recommended (mafft can take quite a bit of memory, so expect slow downs)

build_orth_files(all_orthologs,data_dir)

#Finally, we generate a tree for each gene. Earlier versions we constrained the tree topology, which was faster, but does not allow us to do certain secondary analyses that we will want to, and is probably the wrong way to approach this.

using FLoops
using ProgressMeter

isdir(data_dir*"trees/") || mkdir(data_dir*"trees/")

aligned_genes = filter(endswith(".aligned.fasta"),readdir(data_dir*"aligned/"))

p=Progress(length(aligned_genes),desc="Running IQTree2")
@floop ThreadedEx() for seq in aligned_genes
    run_iqtree(seq)    
    next!(p)
end

finished_trees = filter(endswith(".treefile"),readdir(data_dir*"trees/",join=true))
run_astral(finished_trees)

```

## Calculating ERC

If you are using your own trees, start here!

You will need two specify the species tree and the list of trees to compare.

```{julia}
#Change if using some other species tree.
species_tree = read_tree(data_dir*"trees/astral_consensus.newick")
trees = filter(endswith(".treefile"),readdir(data_dir*"trees/",join=true))

ERC = runERC_files(trees,species_tree;cutoff=5)
#Drop cases with missing data 
ERC = ERC[findall(completecases(ERC)),:]
genes = replace.(filter(endswith(".treefile"),readdir(data_dir*"trees/",join=false)),r".treefile"=>s"")
ERC.i = genes[Int.(ERC.i)]
ERC.j = genes[Int.(ERC.j)]
ERC.gid = [join(sort([x.i,x.j]),"_") for x in eachrow(ERC)]
using Arrow
Arrow.write(data_dir*focal*"_ERC.arrow",ERC)
ERC = DataFrame(Arrow.Table(data_dir*focal*"_ERC.arrow"))

```

## Gene Table Annotation and comparisons

We next build a table that includes all of the gene information. This is based off of the .gff file for your reference of interest.

The chr_dict is just a quick conversion from NCBIs chr ids to something human readable - you'll have to make your own for your system. Note, we drop anything that's on an unmapped scaffold in the process, in our case 6 genes. If you have hundreds of chromosomes/scaffolds, this step can be skipped, or you can use `Julia`s ability to make Dicts iteratively.

```{julia}
using CSV
gff_table = CSV.read(data_dir*focal*"_genes.gff",DataFrame,header=false,skipto=9)
gff_table = gff_table[completecases(gff_table),:]

chr_dict = Dict("NC_004354.4"=>"X","NT_033779.5"=>"2L","NT_033778.4"=>"2R","NT_037436.4"=>"3L","NT_033777.3"=>"3R","NC_004353.4"=>"4","NC_024512.1"=>"Y","NC_024511.2"=>"MT")

gff_table.Column1 = [get(chr_dict,c,"NA") for c in gff_table.Column1]

genes = replace.(filter(endswith(".treefile"),readdir(data_dir*"trees/",join=false)),r".treefile"=>s"")

gene_table = DataFrame(gene=genes,chr="NA",pos_1=0,pos_2=0)
for g in 1:length(genes)
    subtable = gff_table[findall(occursin.(genes[g],gff_table.Column9)),:]
    if size(subtable)[1] > 0
        gene_table.chr[g] = subtable.Column1[1]
        gene_table.pos_1[g] = minimum(subtable.Column4)
        gene_table.pos_2[g] = maximum(subtable.Column5)
    end
end

CSV.write(data_dir*focal*"_gene_table.csv",gene_table)


```

## ERC network analysis

### Broad analysis of scores

We start by looking at the broad set of ERC scores. How do they compare to some potential theoretical nulls, and do they map to any interesting gene features?

```{julia}
gene_table = CSV.read(data_dir*focal*"_gene_table.csv",DataFrame)
using Arrow
ERC = DataFrame(Arrow.Table(data_dir*focal*"_ERC.arrow"))
ERC = ERC[findall(isfinite.(ERC.r)),:]

id_i = indexin(ERC.i,gene_table.gene)
id_j = indexin(ERC.j,gene_table.gene)

ERC.chr_i = gene_table.chr[id_i]
ERC.chr_j = gene_table.chr[id_j]

ERC.pos_i_1 = gene_table.pos_1[id_i]
ERC.pos_i_2 = gene_table.pos_2[id_i]

ERC.pos_j_1 = gene_table.pos_1[id_j]
ERC.pos_j_2 = gene_table.pos_2[id_j]

ERC.dist = missings(Int64,length(ERC.i))
intra = findall(ERC.chr_i .== ERC.chr_j)
ERC.same_chr .= "different"
ERC.same_chr[intra] .= "same"
ERC.dist[intra] = [range_dist([x.pos_i_1,x.pos_i_2],[x.pos_j_1,x.pos_j_2]) for x in eachrow(ERC[intra,:])]

Arrow.write(data_dir*focal*"_ERC_annotated.arrow",ERC)
```

Now we generate some basic summary plots for the data:

```{julia}

ERC = DataFrame(Arrow.Table(data_dir*focal*"_ERC_annotated.arrow"))
using GLMakie, LaTeXStrings
include(srcdir("Plot_utilities.jl"))


fig1 = Figure()
ax1 = Axis(fig1[1,1],
    xlabel="fERC score",
    ylabel="Density",
    xgridvisible=false,
    ygridvisible=false)

hist!(ax1,ERC_sims.fERC,bins=100,
       label="Positive Simulations",normalization=:pdf,
       strokecolor=:purple,color=(:purple,0.5))

hist!(ax1,ERC_null.fERC,bins=100,
       label="Null Expectation",normalization=:pdf,
       strokecolor=:orange,color=(:orange,0.5))

hist!(ax1,ERC.fERC,bins=200,
    label="Real Data",normalization=:pdf,
       strokecolor=:blue,color=(:blue,0.5))
xlims!(ax1,(-5,12.5))

axislegend(ax1,merge=true,unique=true)

ax, hm = hexbin(fig1[1,2],ERC.fERC,ERC.n_edges,
    colormap=[Makie.to_color(:transparent);Makie.to_colormap(:viridis)],
    axis= (; xgridvisible=false,ygridvisible=false,
             xlabel="fERC",ylabel="Shared Edges"),
    colorscale=Makie.pseudolog10,
    bins=(50,50),
    threshold=0)
Colorbar(fig1[1,2][1,2],hm,ticks=[1,100,1000,10000,100000,1000000])

ax2 = Axis(fig1[2,1],yticks=([0.25,0.5],["Same","Different"]),xlabel="fERC",ylabel="Pair on _ chromosomes")

sferc = [ERC.fERC[findall(ERC.same_chr.=="same")],ERC.fERC[findall(ERC.same_chr.=="different")]]
for i in 1:2
    d = density!(sferc[i],offset=i./4,color=:x,colormap=:viridis,colorrange=[-5,10],
    strokecolor=:black,strokewidth=1)
    translate!(d,0,0,-0.1i)
end
xlims!(ax2,(-5,10))

sub_ERC = ERC[findall((!ismissing).(ERC.dist)),:]

ax,hm = hexbin(fig1[2,2],sub_ERC.dist,sub_ERC.fERC,
           colorscale=Makie.pseudolog10,
           bins=(50,50),
           axis=(; xlabel="Pair Distance",
                  ylabel="ERC Score",
                  xscale=Makie.pseudolog10,
                  xticks=([0,10,1000,100000,10000000],[L"0",L"10",L"10^3",L"10^5",L"10^7"]),
                  xgridvisible=false,ygridvisible=false))
Colorbar(fig1[2,2][1,2],hm,ticks=[1,100,1000,10000,100000,1000000])


sub_ERC = ERC[intersect(findall(ERC.chr_i .!= "NA"),findall(ERC.chr_j .!= "NA")),:]

sub_ERC.chr_combo = [join(sort([x.chr_i,x.chr_j]),"-") for x in eachrow(sub_ERC)]

by_chr = groupby(sub_ERC,:chr_combo)

chr_summary = combine(by_chr,
    :r => 
    (r -> (mean=mean(r),
            sd=std(r)))=> AsTable)

sup_fig1_a = @df sub_ERC density(:r,group=(:chr_combo))



```

### Chromosome plot

Julia has no good backend for this (well, neither does R), but I want to plot each pair as a point in a heatmap, with the center of each gene. The issue is converting the location to something meaningful across chromosomes.

Need to have the order of genes consistent between x and y, while accounting for different chromosomes. We'll make dummy X and Y coords here, with the order: 2L,2R,3L,3R,4,X,Y,MT

```{julia}

pos_i = (ERC.pos_i_1 .+ ERC.pos_i_2)./2
pos_j = (ERC.pos_j_1 .+ ERC.pos_j_2)./2


chr_order = ["2L","2R","3L","3R","4","X","Y","MT"]
chr_lengths = [23312347,25254477,28012551,32067996,1271129,23107330,3666928]

pos_i = chr_order_pos(pos_i,ERC.chr_i,chr_order,chr_lengths)
pos_j = chr_order_pos(pos_j,ERC.chr_j,chr_order,chr_lengths)


#Only plot triangle
pos_map1= [minimum([pos_i[x],pos_j[x]]) for x in 1:length(pos_i)]
pos_map2= [maximum([pos_i[x],pos_j[x]]) for x in 1:length(pos_i)]

#We don't actually want to plot 80 million points, instead we summarize into bins.a

wnd_size=100000

binned_ERC = binned_mean(DataFrame(p1=pos_map1,p2=pos_map2,r=ERC.r),wnd_size,wnd_size)

using ColorSchemes
cs = ColorSchemes.viridis
binned_ERC.col = [get(cs,x) for x in binned_ERC.r_mean]

chr_plot = scatter(binned_ERC.x_bin,binned_ERC.y_bin,marker_z=binned_ERC.r_mean,markercolor=cgrad(:viridis),legend=false,alpha=0.5,size=(800,800);
           markershape=:square,markersize=1,markerstrokewidth=0,
           axis=nothing)


savefig(chr_plot,data_dir*focal*"_chr_fig.png")

```

### Generating a "significant" set of edges

### Analysis of significant edges

```{julia}

include(srcdir("ERC_simulations.jl"))
species_tree = read_tree(data_dir*"trees/astral_consensus.newick")

#Negative null - correlations between i.i.d. branch lengths drawn from exponential proportional to the branch lengths.
ERC_null = calculate_ERC_exp_null(species_tree,1000)
disallowmissing!(ERC_null)
ERC_null.fERC = fisher_trans.(ERC_null.r,length(get_branch_lengths(species_tree)))
null_cdf = ecdf(ERC_null.fERC)

ERC.null = null_cdf.(ERC.fERC)
#Positive null - trees that _have_ evolved along the exact same rates, so should show correlations with minor differences.
trees_null = simulate_tree_set(species_tree,40,1000,40,70)
ERC_sims = runERC_collection(trees_null,species_tree;cutoff=5)
disallowmissing!(ERC_sims)
sim_cdf = ecdf(ERC_sims.fERC)
ERC.sims = sim_cdf.(ERC.fERC)

#Take only edges outside of expectation from coalescent sims.
gt_sim = findall(ERC.sims .> 0.95)
#Bonferroni corrected pvalues to get significant edges on the resulting data.
sig_ERC = ERC[gt_sim[findall(ERC.pval[gt_sim] .< 0.05/length(gt_sim))],:]

CSV.write(data_dir*focal*"_sig_ints.tsv",sig_ERC,sep="\t")

#Annotate the gene table.
function indexInERC(gene); findall(ERC.i .== gene .|| ERC.j .== gene);done
idx = map(indexInERC,gene_table.gene)
gene_table.sig_ints = [length(union(findall(sig_ERC.i.==x),findall(sig_ERC.j.==x))) for x in gene_table.gene]
gene_table.mean_r = [mean(ERC.r[idx[i]]) for i in 1:length(idx)]
gene_table.mean_fERC = [mean(ERC.fr[idx[i]]) for i in 1:length(idx)]

CSV.write(data_dir*focal*"_annotated_gene_table.csv",gene_table)



    
gene_pos = chr_order_pos((gene_table.pos_1.+gene_table.pos_2)./2,gene_table.chr,chr_order,chr_lengths)

mean_ERC = scatter(gene_pos,gene_table.mean_r,
           legend=false,
           ylabel="ERC",
           marker_z=gene_table.mean_r,
           c=cgrad(:viridis),
           marings=4mm,xticks=false,permute=(:x,:y);
           markerstrokewidth=0,
           markersize=2)

sig_int_plot = scatter(gene_pos,gene_table.sig_ints .+1,
           legend=false,
           ylabel="Significant Interactions",
           marker_z=gene_table.sig_ints,
           marings=4mm,xticks=false,yscale=:log10,
           yticks=([1,2,11,101,1001],["0","1","10","100","1000"]),
           markercolor=cgrad(["black","red","orange","yellow"],scale=:log10);
           markerstrokewidth=0,
           markersize=2)

full_chr = plot(mean_ERC,chr_plot,sig_int_plot;layout=l)
savefig(full_chr,data_dir*focal*"_fig2.png")
savefig(full_chr,data_dir*focal*"_fig2.pdf")

```

## Plotting significant edges

We next plot the significant edges

```{julia}

pos_i = (sig_ERC.pos_i_1 .+ sig_ERC.pos_i_2)./2
pos_j = (sig_ERC.pos_j_1 .+ sig_ERC.pos_j_2)./2

pos_i = chr_order_pos(pos_i,sig_ERC.chr_i,chr_order,chr_lengths)
pos_j = chr_order_pos(pos_j,sig_ERC.chr_j,chr_order,chr_lengths)

#Only plot lower triangle
pos_map2= [minimum([pos_i[x],pos_j[x]]) for x in 1:length(pos_i)]
pos_map1= [maximum([pos_i[x],pos_j[x]]) for x in 1:length(pos_i)]

scatter!(chr_plot,pos_map1,pos_map2,c=:red;markerstrokewidth=0,markersize=0.5)

chr_lines = [sum(chr_lengths[1:x]) for x in 1:7]
vline!(chr_plot,chr_lines,linecolor=:black)
hline!(chr_plot,chr_lines,linecolor=:black)

savefig(chr_plot,data_dir*focal*"_chr_fig.pdf")

l = @layout [
    a{0.2 w} [b
              c{0.2h}]
]

gene_pos = chr_order_pos((gene_table.pos1.+gene_table.pos2)./2,gene_table.chr,chr_order,chr_lengths)
mean_plot = scatter()
```

## Community detection

We next detect communities of genes based on co-evolutionary interactions. We use the Louvain clustering approach, which tries to maximize modularity within each community (e.g. how dense interactions are within each community versus out of it). Several other approaches may be favorable (Louvain, for instance, does not allow a single gene to belong to multiple communities, when in practice it probably does), but implementation is pending (see wGHAC.py in the src directory).

Here, we first output the graph as a .gml file, which can then be used in the R script for Louvain clustering and in the python script for wGHAC clustering.

```{julia}
using Graphs, SimpleWeightedGraphs, GraphIO, SGtSNEpi
include(srcdir("Graphs_utilities.jl"))

graph = construct_ERC_graph(sig_ERC)

node_IDs = Dict(1:length(unique(union(sig_ERC.i,sig_ERC.j))) .=> sort(unique(union(sig_ERC.i,sig_ERC.j))))

savegraph(datadir*focal*"_graphs.gml",graph,GraphIO.GML.GMLFormat())

#Note: we ignore weights in the Louvain calculation.
communities = Louvain_cluster(graph)

Y = sgtsnepi(graph)


```

Finally, we can generate the clusters using wGHAC, only implementation is currently in python, but I am writing a `Julia` one eventually...

```{python}

```

## GO analysis

The resulting communities are examined for GO category enrichment. The easiest approach here is to use `GOst`, which has a nice implementation in R, so once again we'll step out of Julia for a bit. (But isn't quarto great in that it deals with all three nicely! Thanks Quarto team!)

## Expression analysis

### Tissue

### Timing

## STRING database

The STRING database contains links between genes based on a variety of metrics. Here, we compare the co-evolution scores versus the STRING score, to see at what cut-off we are reaching all likely interactions.

```{julia}

string_db = CSV.read("data/dipterans/String_dmel.detailed.v12.0.txt",DataFrame)
string_alias = CSV.read("data/dipterans/String_dmel_protein_info.txt",DataFrame)


idx = indexin(gene_table.gene,string_alias.alias)
idx = replace(idx,nothing => missing)
gene_table.string_id = missings(String31,length(gene_table.gene))
gene_table.string_id[findall((!ismissing).(idx))] = string_alias.var"#string_protein_id"[idx[findall((!ismissing).(idx))]]

string_db.id1 = indexin(string_db.protein1,gene_table.string_id)
string_db.id2 = indexin(string_db.protein2,gene_table.string_id)
idx = intersect(findall((!isnothing).(string_db.id1)),findall((!isnothing).(string_db.id2)))
string_db = string_db[idx,:]
string_db.gid = [join(sort([gene_table.gene[x.id1],gene_table.gene[x.id2]]),"_") for x in eachrow(string_db)]


joint_tab = innerjoin(ERC,string_db,on=:gid)
```

## Introgression

```{julia}
#Output coordinate file, this will be converted to dmel5 coordinates for vcf analysis, as the vcf we use is mapped to dmel5. 

coords = open(data_dir*"gene_coords.txt","a")

for i in 1:length(gene_table.chr)
    write(coords,gene_table.chr[i]*":"*string(gene_table.pos_1[i])*"-"*string(gene_table.pos_2[i])*"\n")
end

close(coords)


include(srcdir("Introgression_functions.jl"))
using FLoops
using ProgressMeter

vcf="/mnt/d/Projects/CoEvolution/dmel_many.vcf.gz"
pop_file=data_dir*"pops_broadscale.txt"
tree_file=data_dir*"tree_broadscale.txt"

p=Progress(length(gene_table.gene),desc="Running Dsuite")
@floop ThreadedEx() for gene in gene_table.gene
    calculate_df(gene,vcf,pop_file,tree_file)
    next!(p)
end

#Construct introgression table

d_template = CSV.read(data_dir*"whole_genome_tree.txt",DataFrame)
d_template.uid = [join(sort([x.P1,x.P2,x.P3]),"+") for x in eachrow(d_template)]
d_stats = filter(endswith("_tree.txt"),readdir(data_dir*"introgression/",join=true))
d_table = missings(Float64,size(d_template)[1],length(d_stats)) 

for d in 1:length(d_stats)
    tmp = CSV.read(d_stats[d],DataFrame)
    tmp = DataFrame(replace.(eachcol(tmp),NaN=>missing),:auto)
    tmp = tmp[completecases(tmp),:]
    if size(tmp)[1] > 4
        uid = [join(sort([x.x1,x.x2,x.x3]),"+") for x in eachrow(tmp)]
        idx = indexin(uid,d_template.uid)
        abba = tmp.x9
        baba = tmp.x10
        bbaa = tmp.x8
        id2 = findall(tmp.x1 .!= d_template[idx,1])
        df = (abba .- baba) ./ (abba .+ baba .+ bbaa)
        df[id2] = (baba[id2] .- abba[id2]) ./ (abba[id2] .+ baba[id2] .+ bbaa[id2])
        d_table[idx,d] = df
    end
end

cor_mat = cor_test_matrix(d_table,2)

d_names = replace.(filter(endswith("_tree.txt"),readdir(data_dir*"introgression/",join=false)),r"_tree.txt"=>s"")
cor_mat.i = d_names[Int.(cor_mat.i)]
cor_mat.j = d_names[Int.(cor_mat.j)]
cor_mat.gid = [join(sort([x.i,x.j]),"_") for x in eachrow(cor_mat)]
rename!(cor_mat,"r"=>"int_r")
rename!(cor_mat,"pval"=>"int_pval")
using Arrow
Arrow.write(data_dir*focal*"_coInt.Arrow",cor_mat){julia}

```